### ISSUE TITLE
Mavencentral publish

### ISSUE THREAD

**Issue by Nighthawk22** [azagniotov/ant-style-path-matcher#1]
Hi!

Would it be possible to publish this repo to maven? :)

Thanks in advance,
With kind regards
Nighthawk

**Comment by azagniotov** [comment]
Indeed. Stay tuned

**Comment by azagniotov** [comment]
https://issues.sonatype.org/browse/OSSRH-35288

**Comment by azagniotov** [comment]
Please wait for a few hours until the publish will be live:

```
repositories {
    mavenCentral()
}

dependencies {
    compile("io.github.azagniotov:ant-style-path-matcher:1.0.0")
}
```
